sudo: false
language: python
python:
  - "3.7"
install: pip install tox-travis
script: tox

deploy:
  provider: pypi
  user: __token__
  password:
    secure: kNt7X4s+8UTZ2Z8OIOcO9VBHdUaiTGBNKGCmXLlw6OxQkMfO9BREpcX7pS1s2H2kz0YzPyAod1f7yeCPoiqAlG4IngtjuecQdT2PcR89JOVX2XRzcfzS7+CrFHvaLU0ajIK2V3RZqnV3vLGSXvBNSjLd4pbzHNXoKHK3jNuxdWM/OhU4LxIhrV8gVEHsn4j2G1+3EIfSTuk7s4yEhBau4E9PuEB0tX4bi7CjRWl32L2Df0ZjLOgI6U4AQ4jdQAQJEQF2KZ98JaZPflq8iL+n3A9KJBN+88/D3e4LUarZRQLcIWlD2f51Q6BGT3FpQWkwWmh3IZLM7UbEDqidl7yCoGEMb3MNjk2/JIH6q2XxwEVoiJ0QhjSUD/3X8VcoQbJJTKithTpSBk1eH1W4uZhyb0HJuXpWUmSvpNVfdRJ1iyFcD5y2keAgJt9vWLGy28Wmt9CvjtAAU6VHjMBAXKY2s6nwIgm2kMfjOIck6nsTcYAH2SykZ0Jblc+yt7Y+ABRW458PLn3oSGRFXd9VZW92HQAYjCyaC2HbkgZwVgsK1BLM/ylRrYsdX0B79ydBrUp/iRFkIwYN59Vb2XdNwsXjb/V//Vfiin+ll8zoyEXZMH6BRjC6OAwWRm2EcQMcGdNP/t/S3xRgkmwlVrgA8pBeZfbyJp4jSMgU3sOIjEtJa8s=
  on:
    tags: true
    repo: HeMan/jobbergate
